package com.moip.exceptions;

/**
 * This exception represents the class of errors generated by the user (not
 * system fault). Usually this is the equivalent of the 4xx HTTP error classes
 * and the applications' exception mapper handles it returned the better 4xx
 * error to the user.
 */
public class UserException extends ApplicationException {
    private static final long serialVersionUID = 5159913781729993872L;

    public UserException(final UserErrorCode code) {
        super(code);
    }

    public UserException(final UserErrorCode code, final Throwable cause) {
        super(code, cause);
    }
}
